# Generated by Django 5.1.5 on 2025-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('municipio', models.CharField(max_length=100)),
                ('residencia', models.CharField(max_length=100)),
                ('productos', models.TextField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('roscas', 'Roscas'), ('suspiros', 'Suspiros'), ('galletas', 'Galletas'), ('bizcochos', 'Bizcochos')], default='roscas', max_length=50),
        ),
    ]
